package igu;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logica.Cartelera;
//import javax.swing.JOptionPane;
import logica.controlador.CarteleraController;

public class EditarPelicula extends javax.swing.JFrame {

    private final CarteleraController controller;
    private final int id;/*Creo el atributo Id que es donde se va a referenciar la modificación*/

    public EditarPelicula(CarteleraController controller, int id) {/*Creo mis constructores*/
        this.controller = controller;
        this.id = id;
        initComponents();/*el initComponents me carga la interfaz grafica*/
        setLocationRelativeTo(null);
        cargarDatos();/*Si yo hago esto me ahorro de hacer la linea 20 y permito que me cargue
        todos los datos al inicializar la ventana*/


        // --- COMIENZO DEL CÓDIGO AÑADIDO ---
        // 1. Carga la imagen de 128x128 píxeles
        var url = getClass().getResource("/logoCineMagenta128x128.png");

        // 2. Escala la imagen para que encaje en el JLabel
        if (url != null) {
            ImageIcon originalIcon = new ImageIcon(url);
            Image scaledImage = originalIcon.getImage()
                    .getScaledInstance(jLabel7.getWidth(), jLabel7.getHeight(), Image.SCALE_SMOOTH);

            // 3. Establece la imagen en el JLabel
            jLabel7.setIcon(new ImageIcon(scaledImage));
        }

        // --- FIN DEL CÓDIGO AÑADIDO ---
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGrabarCambios = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        cmbGenero = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtDirector = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(120, 120, 121));

        jLabel1.setText("Nombre");

        jLabel2.setText("Director");

        jLabel3.setText("Año");

        jLabel4.setText("Duración");

        jLabel5.setText("Genero");

        btnGrabarCambios.setText("Grabar Cambios");
        btnGrabarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarCambiosActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Comedia", "Drama", "Acción", "Terror", "Ciencia Ficción", "Aventura" }));
        cmbGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGeneroActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirectorActionPerformed(evt);
            }
        });

        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });

        txtDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EDITAR PELÍCULA DE NUESTRA CARTELERA");

        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGrabarCambios)
                                .addGap(226, 226, 226)
                                .addComponent(btnLimpiar))
                            .addComponent(txtNombre)
                            .addComponent(txtDirector)
                            .addComponent(txtAnio)
                            .addComponent(txtDuracion)
                            .addComponent(cmbGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 219, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGrabarCambios)
                            .addComponent(btnLimpiar))
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        /*Aquí vamos a indicarle al botón que me limpie todos los campos*/
        onLimpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGrabarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarCambiosActionPerformed
        onGuardar();
    }//GEN-LAST:event_btnGrabarCambiosActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirectorActionPerformed

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void txtDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionActionPerformed

    private void cmbGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGeneroActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrabarCambios;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    // ==== LÓGICA ====

    private void cargarDatos() {
        try {
            Cartelera c = controller.onBuscarPorId(id);
            if (c == null) {
                JOptionPane.showMessageDialog(this, "No existe la película id=" + id, "Editar", JOptionPane.ERROR_MESSAGE);
                dispose();
                return;
            }
            txtNombre.setText(c.getTitulo());
            txtDirector.setText(c.getDirector());
            txtAnio.setText(String.valueOf(c.getAnio()));
            txtDuracion.setText(String.valueOf(c.getDuracion()));
            // set género
            String g = c.getGenero() != null ? c.getGenero().name() : "-";
            cmbGenero.setSelectedIndex(switch (g) {
                case "COMEDIA" -> 1; case "DRAMA" -> 2; case "ACCION" -> 3;
                case "TERROR" -> 4; case "CIENCIA_FICCION" -> 5; case "AVENTURA" -> 6;
                default -> 0;
            });
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar: " + ex.getMessage(), "Editar", JOptionPane.ERROR_MESSAGE);
            dispose();
        }
    }

    private void onLimpiar() {
        txtNombre.setText("");
        txtDirector.setText("");
        txtAnio.setText("");
        txtDuracion.setText("");
        cmbGenero.setSelectedIndex(0);
    }

    private void onGuardar() {
        try {
            if (txtNombre.getText().isBlank() || txtDirector.getText().isBlank()
                || txtAnio.getText().isBlank() || txtDuracion.getText().isBlank()
                || cmbGenero.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Editar", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int anio = Integer.parseInt(txtAnio.getText().trim());
            int dur = Integer.parseInt(txtDuracion.getText().trim());
            String generoStr = (String) cmbGenero.getSelectedItem();
            Cartelera.Genero genero = switch (generoStr) {
                case "Comedia" -> Cartelera.Genero.COMEDIA;
                case "Drama" -> Cartelera.Genero.DRAMA;
                case "Acción" -> Cartelera.Genero.ACCION;
                case "Terror" -> Cartelera.Genero.TERROR;
                case "Ciencia Ficción" -> Cartelera.Genero.CIENCIA_FICCION;
                case "Aventura" -> Cartelera.Genero.AVENTURA;
                default -> throw new IllegalArgumentException("Género no válido");
            };

            controller.onActualizarPelicula(
                id,
                txtNombre.getText().trim(),
                txtDirector.getText().trim(),
                anio,
                dur,
                genero
            );

            JOptionPane.showMessageDialog(this, "Película modificada correctamente.", "Editar", JOptionPane.INFORMATION_MESSAGE);
            new ListadoPeliculas(controller).setVisible(true);
            dispose();
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Año y Duración deben ser números.", "Editar", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al modificar: " + ex.getMessage(), "Editar", JOptionPane.ERROR_MESSAGE);
        }
    }
}
