package igu;

import java.awt.Image;
import javax.swing.ImageIcon;
import logica.controlador.CarteleraController;

public class MainMenu extends javax.swing.JFrame {

    private final CarteleraController controller;

    /**
     * Creates new form MainMenu
     */
    public MainMenu(CarteleraController controller) {
        if (controller == null) throw new IllegalArgumentException("controller nulo");
        this.controller = controller;
        initComponents();
        
        configurarMenuBar(); // Actualizacion
        
        jPanel1.setBackground(new java.awt.Color(120, 120, 121));

        // --- COMIENZO DEL CÓDIGO AÑADIDO ---
        // 1. Carga la imagen de 128x128 píxeles
        var url = getClass().getResource("/logoCineMagenta128x128.png");

        // 2. Escala la imagen para que encaje en el JLabel
        if (url != null) {
            ImageIcon originalIcon = new ImageIcon(url);

            // Aquí se define el tamaño
            Image scaledImage = originalIcon.getImage().getScaledInstance(128, 128, Image.SCALE_SMOOTH);

            // 3. Establece la imagen en el JLabel
            jLabel2.setIcon(new ImageIcon(scaledImage));
        } else {
            System.err.println("⚠ No se encontró el recurso: /logoCineMagenta128x128.png");
        }
        // --- FIN DEL CÓDIGO AÑADIDO ---
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jButton1.setText("Agregar Película");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Revisar Listado de Películas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // === Barra de menús (JMenuBar) === // Actualizacion
    private void configurarMenuBar() {
        javax.swing.JMenuBar menuBar = new javax.swing.JMenuBar();

        // --- Menú Películas ---
        javax.swing.JMenu menuPeliculas = new javax.swing.JMenu("Películas");

        javax.swing.JMenuItem miListado = new javax.swing.JMenuItem("Ver listado…");
        miListado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
                java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miListado.addActionListener(e -> new ListadoPeliculas(controller).setVisible(true));

        javax.swing.JMenuItem miAgregar = new javax.swing.JMenuItem("Agregar nueva…");
        miAgregar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
                java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miAgregar.addActionListener(e -> new AgregarPelicula(controller).setVisible(true));

        menuPeliculas.add(miListado);
        menuPeliculas.add(miAgregar);

        // --- Menú Ayuda ---
        javax.swing.JMenu menuAyuda = new javax.swing.JMenu("Ayuda");
        javax.swing.JMenuItem miAcerca = new javax.swing.JMenuItem("Acerca de CineMagenta");
        miAcerca.addActionListener(e -> javax.swing.JOptionPane.showMessageDialog(this,
                "CineMagenta v3.0 - S8\nActualizado por Francisco Henríquez\nDUOC UC - POO 2",
                "Acerca de", javax.swing.JOptionPane.INFORMATION_MESSAGE));
        menuAyuda.add(miAcerca);

        menuBar.add(menuPeliculas);
        menuBar.add(menuAyuda);
        setJMenuBar(menuBar);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AgregarPelicula(controller).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new ListadoPeliculas(controller).setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    // ⚠️ Método no utilizado en la versión final.
    // El controller se inyecta desde CineMagenta.main().
    //
    @Deprecated
    private CarteleraController crearControllerPorDefecto() {
        persistencia.ControladoraPersistencia repo = new persistencia.ControladoraPersistencia();
        logica.ICarteleraService jpa = new logica.JpaCarteleraService(repo);
        logica.ICarteleraService decorado = new logica.decorador.LoggingCarteleraService(
                new logica.decorador.ValidatingCarteleraService(jpa));
        return new logica.controlador.CarteleraController(decorado);
    }

}
